In [178]:
a = np.array([2,23,4])

[ 2 23  4]


In [179]:
b = np.array([2,23,4],dtype=np.int32)
print(b.dtype)

int32


In [180]:
b = np.array([2,23,4],dtype=np.int32)
print(b.dtype)
c = np.array([2,23,4],dtype=np.float16)
print(c.dtype)
b = np.array([[2,23,4],
             [2,32,4]])
print(b)
a = np.zeros((3,4))
print(a)
a = np.ones((5,7),dtype=np.int16)
print(a)

float16


In [181]:
b = np.array([[2,23,4],
             [2,32,4]])
print(b)

[[ 2 23  4]
 [ 2 32  4]]


In [182]:
a = np.zeros((3,4))
print(a)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [183]:
a = np.ones((5,7),dtype=np.int16)
print(a)

[[1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1]]


In [184]:
g = np.empty((3,4))
print(g)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [185]:
h = np.arange(10,20,2)

print(h)

[10 12 14 16 18]


In [186]:
e=np.arange(15).reshape((3,5))
print(e)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]


In [187]:
k = np.linspace(1,10,5)
print(k)

[ 1.    3.25  5.5   7.75 10.  ]


In [188]:
k = (np.linspace(1,10,20).reshape((4,5)))m
print (k)

SyntaxError: invalid syntax (<ipython-input-188-6e681dbd00ea>, line 1)

In [189]:
a = np.array([10,20,30,40])
b=np.arange(4)

In [190]:
print (a,b,a+b, 1+b)

[10 20 30 40] [0 1 2 3] [10 21 32 43] [1 2 3 4]


In [191]:
s = pd.Series([1,3,5, np.nan, 59, 1])

In [192]:
print(s)

0     1.0
1     3.0
2     5.0
3     NaN
4    59.0
5     1.0
dtype: float64


In [193]:
dates = pd.date_range('201809', periods = 12)
print(dates)
df = pd.DataFrame(np.random.randn(1,7), index = dates, columns = "will")
print(df)

ValueError: could not convert string to Timestamp

In [194]:
print (dates)

DatetimeIndex(['2018-09-27', '2018-09-28', '2018-09-29', '2018-09-30',
               '2018-10-01', '2018-10-02', '2018-10-03', '2018-10-04',
               '2018-10-05', '2018-10-06', '2018-10-07', '2018-10-08'],
              dtype='datetime64[ns]', freq='D')


In [195]:
df = pd.DataFrame(np.random.randn(6,4),index = dates, columns = ['a','b','c','d'])

ValueError: Shape of passed values is (4, 6), indices imply (4, 12)

In [196]:
print (df)

                   a         b         c         d
2018-01-01 -0.600500 -0.869459  0.186710 -0.335519
2018-01-02 -0.101384 -0.395094 -1.309345  0.295862
2018-01-03  0.410624 -1.603005 -0.149076 -0.065611
2018-01-04  0.941885  1.690935  0.325148 -2.361440
2018-01-05 -0.360212 -0.212462 -1.002158  0.717103
2018-01-06  0.485886 -0.717495 -1.815890 -0.015393


In [176]:
df1 = pd.DataFrame(np.arange(12).reshape((3,4)))

In [157]:
df1

0  1   2   3
0  0  1   2   3
1  4  5   6   7
2  8  9  10  11

In [ ]:
df2 = pd.DataFrame({'A':1.,
                   'B':pd.Timestamp('2013')})

In [45]:

sum = 0
for i in range(10):
    sum = sum + i
    print (sum)

0
1
3
6
10
15
21
28
36
45


In [50]:
x = 5
y =8

if x > y :
    print('x is greater than y')
else:
    print('x is less than y')
    
if x != y:
    print('x is not equal to y')

x is less than y
x is not equal to y


In [52]:

marks = int(input("enter your marks:"))
if marks>=35:
    print("you passed the exam")
else:
    print("oops, you fail the exam")
print("Thanks")

enter your marks:40
you passed the exam
Thanks


In [60]:
print ("before")
num_moons = 5
while num_moons >0:
    print (num_moons)
    num_moons -= 1
print("after")

before
5
4
3
2
1
after


In [69]:
for i in range(1,10):
    if i == 6:
         continue
    print(i)

1
2
3
4
5
7
8
9


In [68]:
for i in [1,2,3,4,5]:

    print(i)

1
2
3
4
5


In [71]:
for i in range(1,10):
    if i == 6:
         continue
    print(i)
num = 2
while num <= 1000:
    is_prime = True
    trial = 2
    while trial <num:
        if(num % trial) == 0:
            is_prime = False
        trial += 1
    if is_prime:
        print (num)
    num += 1

2
3
5
7
11
13
17
19
23
29
31
37
41
43
47
53
59
61
67
71
73
79
83
89
97
101
103
107
109
113
127
131
137
139
149
151
157
163
167
173
179
181
191
193
197
199
211
223
227
229
233
239
241
251
257
263
269
271
277
281
283
293
307
311
313
317
331
337
347
349
353
359
367
373
379
383
389
397
401
409
419
421
431
433
439
443
449
457
461
463
467
479
487
491
499
503
509
521
523
541
547
557
563
569
571
577
587
593
599
601
607
613
617
619
631
641
643
647
653
659
661
673
677
683
691
701
709
719
727
733
739
743
751
757
761
769
773
787
797
809
811
821
823
827
829
839
853
857
859
863
877
881
883
887
907
911
919
929
937
941
947
953
967
971
977
983
991
997


In [84]:
n = 5^3
print (n)

6


In [86]:
def function(x):
    return 3*x
a = function(3)
print(a)

9


In [88]:
def function2(x,y):
    return x+y
m = function2(3,9)
print (m)

12


# extracting

In [93]:
file = pd.read_csv('date_parser')

FileNotFoundError: File b'date_parser' does not exist

In [97]:

print("coke")

coke


In [106]:
import numpy as np
a = len("double")
print(a)
b = 'message'
print(b.count('e'))

6
2


In [134]:
n = 'hello world'
n = n.replace('world','whole whold')
print (n)

hello whole whold


In [130]:
name1 = "alfa"
h1=1.70
w1=65
name2 = "beta"
h2 = 1.75
w2=70
name3 = "sigma"
h3 = 1.90
w3 = 120

In [131]:
def bmi(name, h, w):
    bmi = w / (h ** 2)
    print("bmi: ")
    print(bmi)
    if bmi < 25:
        return name + " is not over weight"
    else:
        return name + " is over weight"

In [132]:
result1 = bmi(name1, h1, w1)
result2 = bmi(name2, h2, w2)
result3 = bmi(name3, h3, w3)

bmi: 
22.49134948096886
bmi: 
22.857142857142858
bmi: 
33.2409972299169


In [133]:
print(result1)
print(result2)
print(result3)

alfa is not over weight
beta is not over weight
sigma is over weight
