In [4]:
import numpy as np
import numpy.ma as ma
import pandas as pd

In [11]:
array = np.array([[1,2,3],[2,3,4]],[[3,4,5],[])
print(array)

[[1 2 3]
 [2 3 4]
 [3 4 5]]


In [12]:
print('number of dim:', array.ndim)

number of dim: 2


In [13]:
print('shape:', array.shape)

shape: (3, 3)


In [14]:
print('size', array.size)

size 9
