# A NumPy tutorial

In [7]:
import numpy as np

## Creating an array with a certain shape

In [65]:
aa = np.array([[1,2,3,4],[2,3,4,5],[8,9,10,11]])
print(aa)

[[ 1  2  3  4]
 [ 2  3  4  5]
 [ 8  9 10 11]]


In [66]:
a = np.array([[1,2,3,4],[2,3,4,5],[8,9,10,]])
print(a)

[list([1, 2, 3, 4]) list([2, 3, 4, 5]) list([8, 9, 10])]


In [67]:
a = np.array([[1,2,3,4],[2,3,4,5],[8,9,10,11]])
print(a)

[[ 1  2  3  4]
 [ 2  3  4  5]
 [ 8  9 10 11]]


In [8]:
a = np.arange(24).reshape(6, 4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [9]:
a.shape

(6, 4)

In [10]:
a.ndim

2

In [11]:
a.dtype.name

'int64'

In [12]:
a.itemsize

8

In [13]:
a.size

24

In [14]:
type(a)

numpy.ndarray

## Explicit array creation

In [75]:
b = np.array([6, 12, 35])
b

array([ 6, 12, 35])

In [76]:
type(b)

numpy.ndarray

In [77]:
b.dtype

dtype('int64')

In [78]:
c = np.array([2,5.2,4.3555])
c

array([2.    , 5.2   , 4.3555])

In [79]:
c.dtype

dtype('float64')

In [80]:
# Always provide a single list of numbers as arguments!
a = np.array(3,5,7,13)    # WRONG
a

ValueError: only 2 non-keyword arguments accepted

In [81]:
a = np.array([3,5,7,13])  # RIGHT
a

array([ 3,  5,  7, 13])

In [82]:
# array transforms sequences of sequences into two-dimensional arrays
b = np.array([(5.5,3.1,2.3), (4.0,5.0,.6)])
b

array([[5.5, 3.1, 2.3],
       [4. , 5. , 0.6]])

In [83]:
#complex arrays
c = np.array( [ [1,2], [3,4] ], dtype=complex )
c

array([[1.+0.j, 2.+0.j],
       [3.+0.j, 4.+0.j]])

In [84]:
np.zeros( (5,7) )

array([[0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.]])

In [85]:
np.ones( (2,3,4), dtype=np.int16 ) 

array([[[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]]], dtype=int16)

In [86]:
np.empty( (3,5) )        

array([[0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
        0.00000000e+000, 0.00000000e+000],
       [0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
        3.10503618e+231, 3.10503618e+231],
       [3.10503618e+231, 4.34006569e-311, 2.96439388e-323,
        0.00000000e+000, 0.00000000e+000]])

## Create an array as a sequence of numbers

In [87]:
# Integers
np.arange( 20, 64, 5 )

array([20, 25, 30, 35, 40, 45, 50, 55, 60])

In [88]:
# Floats
np.arange( 0, 16.2, 0.5 )                 # it accepts float arguments

array([ 0. ,  0.5,  1. ,  1.5,  2. ,  2.5,  3. ,  3.5,  4. ,  4.5,  5. ,
        5.5,  6. ,  6.5,  7. ,  7.5,  8. ,  8.5,  9. ,  9.5, 10. , 10.5,
       11. , 11.5, 12. , 12.5, 13. , 13.5, 14. , 14.5, 15. , 15.5, 16. ])

### linspace: linspace(start, stop, num=50, endpoint=True, retstep=False)

#### returns an ndarray, consisting of 'num' equally spaced samples in the closed interval [start, stop] or the half-open interval [start, stop). If a closed or a half-open interval will be returned, depends on whether 'endpoint' is True or False. 

In [6]:
np.linspace( 0, 4, 5, )                 # 15 numbers from 0 to 3

array([0., 1., 2., 3., 4.])

In [90]:
from numpy import pi
x = np.linspace( 0, 2*pi, 16 )        # useful to evaluate function at many points
f = np.sin(x)
f

array([ 0.00000000e+00,  4.06736643e-01,  7.43144825e-01,  9.51056516e-01,
        9.94521895e-01,  8.66025404e-01,  5.87785252e-01,  2.07911691e-01,
       -2.07911691e-01, -5.87785252e-01, -8.66025404e-01, -9.94521895e-01,
       -9.51056516e-01, -7.43144825e-01, -4.06736643e-01, -2.44929360e-16])

### Time Comparison between Python Lists and Numpy Arrays

In [91]:
import time
size_of_vec = 100000
def pure_python_version():
    t1 = time.time()
    X = range(size_of_vec)
    Y = range(size_of_vec)
    Z = []
    for i in range(len(X)):
        Z.append(X[i] + Y[i])
    return time.time() - t1

In [92]:
def numpy_version():
    t1 = time.time()
    X = np.arange(size_of_vec)
    Y = np.arange(size_of_vec)
    Z = X + Y
    return time.time() - t1

In [93]:
t1 = pure_python_version()
t2 = numpy_version() + 0.000000001
print(t1, t2)
print("Numpy is in this example " + str(t1/t2) + " faster!")

0.030458927154541016 0.0006220350728759766
Numpy is in this example 48.96657517029433 faster!


## Printing arrays

In [94]:
from numpy  import *

a = arange(15).reshape(3, 5)
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [95]:
a = arange(6)                         # 1d array
print(a)

[0 1 2 3 4 5]


In [96]:
b = arange(12).reshape(4,3)           # 2d array
print(b)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


In [97]:
c = arange(24).reshape(2,3,4)         # 3d array
print(c)

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]


In [98]:
print(arange(10000))

[   0    1    2 ... 9997 9998 9999]


In [99]:
print(arange(10000).reshape(100,100))

[[   0    1    2 ...   97   98   99]
 [ 100  101  102 ...  197  198  199]
 [ 200  201  202 ...  297  298  299]
 ...
 [9700 9701 9702 ... 9797 9798 9799]
 [9800 9801 9802 ... 9897 9898 9899]
 [9900 9901 9902 ... 9997 9998 9999]]


In [100]:
a = array( [20,30,40,50] )
a

array([20, 30, 40, 50])

In [101]:
b = arange( 4 )
b

array([0, 1, 2, 3])

### Artithmetic operations

In [102]:
c = a-b
c

array([20, 29, 38, 47])

In [106]:
d = a+b
d

array([20, 31, 42, 53])

In [107]:
res = a**2
print(res)

[ 400  900 1600 2500]


In [108]:
res2 = 10*sin(a)
print(res2)

[ 9.12945251 -9.88031624  7.4511316  -2.62374854]


In [109]:
b**2
10*sin(a)
a<35

array([ True,  True, False, False])

### Matrix operations

In [110]:
print(a)
print(b)

[20 30 40 50]
[0 1 2 3]


In [111]:
a*b

array([  0,  30,  80, 150])

In [112]:
dot(a,b)

260

In [113]:
A = array( [[1,1],
...             [0,1]] )
B = array( [[2,0],
...             [3,4]] )
A*B                         # elementwise product

array([[2, 0],
       [0, 4]])

In [114]:
dot(A,B)                    # matrix product

array([[5, 4],
       [3, 4]])

In [123]:
a = ones((2,3), dtype=int)
b = random.random((2,3))
a *= 3
a

array([[3, 3, 3],
       [3, 3, 3]])

In [124]:
b += a
b

array([[3.37801568, 3.43448948, 3.03292378],
       [3.83219067, 3.94373907, 3.32003041]])

In [142]:
#axis
b = arange(12).reshape(3,4)
b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [143]:
b.sum(axis=0)                            # sum of each column

array([12, 15, 18, 21])

In [144]:
b.min(axis=1)                            # min of each row

array([0, 4, 8])

In [145]:
b.cumsum(axis=1)                         # cumulative sum along each row

array([[ 0,  1,  3,  6],
       [ 4,  9, 15, 22],
       [ 8, 17, 27, 38]])

## Indexig & Slicing

In [146]:
a = np.arange(10)**3
a

array([  0,   1,   8,  27,  64, 125, 216, 343, 512, 729])

In [147]:
a[3]

27

In [148]:
a[5:9]

array([125, 216, 343, 512])

In [149]:
a[:6:2] = -100
a
# from strat to position 6 evry other elem to be set to -100

array([-100,    1, -100,   27, -100,  125,  216,  343,  512,  729])

### Multidimensional arrays can have one index per axis
These indices are given in a Tuple separated by commas

In [150]:
def f(x,y):
    return 10*x + y
    
b = np.fromfunction(f, (5,4), dtype=int)
b

array([[ 0,  1,  2,  3],
       [10, 11, 12, 13],
       [20, 21, 22, 23],
       [30, 31, 32, 33],
       [40, 41, 42, 43]])

In [81]:
b[2,3]

23

In [82]:
b[0:5,1]
# each row in the 2nd column of b

array([ 1, 11, 21, 31, 41])

In [83]:
b[:,1]
#equivalent

array([ 1, 11, 21, 31, 41])

In [84]:
b[1:3,:]
# each column in the 2nd & 3rd row of b

array([[10, 11, 12, 13],
       [20, 21, 22, 23]])

### Iterating over multidimensional arrays is done with respect to the first axis

In [85]:
for row in b:
    print(row)

[0 1 2 3]
[10 11 12 13]
[20 21 22 23]
[30 31 32 33]
[40 41 42 43]


## Copy()

In [152]:
#deep copy vs shallow copy
import numpy as np
x = np.array([[11,22,33],[44,55,66]], order='F')
y = x.copy()
z = x
x[0,0] = 1001
print(x)
print(y)
print(z)

[[1001   22   33]
 [  44   55   66]]
[[11 22 33]
 [44 55 66]]
[[1001   22   33]
 [  44   55   66]]


### The eye function

#### returns a 2-D array with ones on the diagonal and zeros elsewhere

In [87]:
np.eye(5, 8, k=1, dtype=int)

array([[0, 1, 0, 0, 0, 0, 0, 0],
       [0, 0, 1, 0, 0, 0, 0, 0],
       [0, 0, 0, 1, 0, 0, 0, 0],
       [0, 0, 0, 0, 1, 0, 0, 0],
       [0, 0, 0, 0, 0, 1, 0, 0]])

## Broadcasting

### Broadcasting is a powerful mechanism that allows numpy to work with arrays of different shapes when performing arithmetic operations. 
Frequently we have a smaller array and a larger array, and we want to use the smaller array multiple times to perform some operation on the larger array.

In [88]:
# Add the vector v to each row of the matrix x, storing the result in the matrix y
x = np.array([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12]])
v = np.array([1, 0, 1])
y = np.empty_like(x)   # Create an empty matrix with the same shape as x

In [89]:
# Add the vector v to each row of the matrix x with an explicit loop
for i in range(4):
    y[i, :] = x[i, :] + v
print(y)

[[ 2  2  4]
 [ 5  5  7]
 [ 8  8 10]
 [11 11 13]]


In [90]:
# However when the matrix x is very large, computing an explicit loop in Python could be slow
vv = np.tile(v, (4, 1))  # Stack 4 copies of v on top of each other
print(vv)                # Prints "[[1 0 1]
                         #          [1 0 1]
                         #          [1 0 1]
                         #          [1 0 1]]"
y = x + vv  # Add x and vv elementwise
print(y)

[[1 0 1]
 [1 0 1]
 [1 0 1]
 [1 0 1]]
[[ 2  2  4]
 [ 5  5  7]
 [ 8  8 10]
 [11 11 13]]


In [91]:
# Numpy broadcasting allows us to perform this computation without actually creating multiple copies of v
y = x + v  # Add v to each row of x using broadcasting
print(y)

[[ 2  2  4]
 [ 5  5  7]
 [ 8  8 10]
 [11 11 13]]


## Some applications of broadcasting:

### Compute outer product of vectors

In [92]:
v = np.array([1,2,3])  # v has shape (3,)
w = np.array([4,5])    # w has shape (2,)

In [93]:
# To compute an outer product, first reshape v to be a column vector of shape (3, 1)
# then broadcast it against w to yield an output of shape (3, 2), which is the outer product of v and w:
# [[ 4  5]
#  [ 8 10]
#  [12 15]]
print(np.reshape(v, (3, 1)) * w)

[[ 4  5]
 [ 8 10]
 [12 15]]


### Add a vector to each row of a matrix

In [94]:
x = np.array([[1,2,3], [4,5,6]])
# x has shape (2, 3) and v has shape (3,) so they broadcast to (2, 3), giving the following matrix:
# [[2 4 6]
#  [5 7 9]]
print(x + v)

[[2 4 6]
 [5 7 9]]


In [95]:
# Add a vector to each column of a matrix - x has shape (2, 3) and w has shape (2,).
# If we transpose x then it has shape (3, 2) and can be broadcast against w to yield a result of shape (3, 2)
# transposing this result yields the final result of shape (2, 3) which is the matrix x with
# the vector w added to each column. Gives the following matrix:
# [[ 5  6  7]
#  [ 9 10 11]]
print((x.T + w).T)

[[ 5  6  7]
 [ 9 10 11]]


In [96]:
# Another solution is to reshape w to be a row vector of shape (2, 1);
# we can then broadcast it directly against x to produce the same output.
print(x + np.reshape(w, (2, 1)))

[[ 5  6  7]
 [ 9 10 11]]


### Multiply a matrix by a constant

In [97]:
# x has shape (2, 3). Numpy treats scalars as arrays of shape ();
# these can be broadcast together to shape (2, 3), producing the following array:
# [[ 2  4  6]
#  [ 8 10 12]]
print(x * 2)

[[ 2  4  6]
 [ 8 10 12]]
